app <- ShinyDriver$new("../../")
app$snapshotInit("val-tab-submit")

app$waitFor("false", timeout = 5000)
app$setInputs(validate_btn = "click")
app$snapshot()
app$setInputs(`study-study_exists` = "No")
app$setInputs(`study-study_text` = "test")
app$snapshot()
app$setInputs(validate_btn = "click")
app$snapshot()
