repos:
-   repo: https://github.com/lorenzwalthert/pre-commit-hooks
    rev: v0.0.0.9016
    hooks:
    -   id: style-files
        exclude: 'renv/activate.R'
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: readme-rmd-rendered
    -   id: use-tidy-description
    -   id: lintr
