# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
- 3.4
- oldrel
- release
- devel
jobs:
  include:
    - if: type = pull_request
      stage: lint
      r: release
      script:
        - |
          R CMD INSTALL $PKG_TARBALL
          Rscript -e 'lintr::lint_package()'
    - stage: deploy
      before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        skip_cleanup: true

r_github_packages:
  - jimhester/lintr
  - rstudio/rmarkdown

after_success:
  - Rscript -e 'covr::codecov()'

env:
  global:
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
    - secure: Uo9k4bc2DH/4PRffWcbRqvNuJiNsLg3cD8yA1eji9+pzIU5lrLY//EzneUkLV92RxXpKZbpuDgizcPUj1OWpblInlOStb7lgiGq/e+fkAv8H1v48cdcmrGzVDi/Ylt0xDATbxSH7frdzrMDsHv1QmY7699krSuzz2xb45a7d7WhoksK+6U9rpi78CGNadtwz/qSGStkE8lE5Ehg/++3UPC2FySRxXM6XQUwRUUuExz7tUeYqINLj8dZSWcwinceZ0awkldAvfH1GW+ITWmDQTcGt3FpyUXha6/kKSfM6opLWCJD9L8wv043ubaGhsbdtwuQ6Y1lRXwibMBhYOTvaOZQpEmWQB97cppo32ozuSD6TkBHZbINM4mbV6OIOEYFgnnGiJ+ahbg/FfsfKpUypNCFPuVdbbTDLb13nLSnY+iikck8/prqU9xbEIl/q/xi5hciu4aqqpkvbmqjdjRaatHK9/PDONDmQB11tZp9e5h/qbdUJAfaSaqKsJK0JUsRW88H15WhVGzzq5bwVGj8uA0noUUnLDYC6NdgQfBrw5XgsvM/e/JojFM4ItPpvw+EBd+Aeul3ytOzwrpH4aGTsF3ZzMEAxV0ur1P57Fwp1oPZEYnaDNRoPvL/z0oCdr8k4V7j/vFF8aDR9E3txBPqUv71i9DI+0DYEEkuNRZ8YgPI=
    - secure: IzgB3ykXOwU+swYXR8Ftex9F7XeI0zhYo7MQgCcvNj+yiUJO9iMvkOBzQxu8yW00aqNOetk1kGnsPBRqTffqlFjCCmchIisFsy0OdhPielBn2089w/B4Vm8SKfS8ElXpo+qCU7lL69EIARft2miG7i8DNQ2vRNPIzeUqIYAhWupXgkfHGS9HuZoSGsX+DIQQ3Df/6LPgmSc90p1WcrxRLIKtyNcV+WRdOkKnY+iNkWsWzTcwnxAlb8SQyuUZomyfs8/GZnzJmJO3q6cr1/25j0MjQmlit6hq6FN7Ed34/qUttPJhmObZKlL03Tyw/vDcauN4XyXKaOgrhC9rPjKqHY3ZrXM3ETnzQ2ZDjhKTzt1ujGCr7ZJ+FI5xHwaIYQ83JYDX1dlqxTL6h9n/GIA+ZpmSn7eHNWUh+f4NgEXdE2GidIxv/egzge7RbOAfdr2jVZmRwXQMpAXZ/kUsBzjJovkju5UTbuJBzq9mVKl+S8VTbRAOB7Kx2vYeDVxxaEtMgf/qZZMF1IGwmPbLtjL12mOuYYkK5Av/6mStUELO7GIWLxH5LgDOSDT8t17ssRFxuXTDZndQuUh329y9LK/SyKiMT0aayZ2mgME/I7cEKk/CphTwsmTndL1Y94uqDAhJgqCUNytzv6cwQW31YRqnkjFKyc9vzj1Kh+DIXQlKdX0=
