default:
  production: TRUE
  app_url: "https://shinypro.synapse.org/users/nkauer/dccvalidator-test/"
  parent: "syn20400157"
  path_to_markdown: "inst/using-the-dccvalidator-app-amp-ad.Rmd"
  study_table: "syn11363298"
  samples_table: "syn21578908"
  annotations_table: "syn10242922"
  annotations_link: "https://shinypro.synapse.org/users/nsanati/annotationUI/"
  templates_link: "https://www.synapse.org/#!Synapse:syn18512044"
  docs_tab:
    include_tab: TRUE
    include_upload_widget: TRUE
    tab_name: "Upload Study Documentation"
    path_to_docs_markdown: "inst/study-documentation-amp-ad.Rmd"
  teams:
    - "273957"
  include_biospecimen_type: FALSE
  templates:
    manifest_template: "syn20820080"
    individual_templates:
      human: "syn12973254"
      mouse or other animal model: "syn12973253"
    biospecimen_templates:
      mouse or other animal model: "syn12973252"
      human: "syn12973252"
      drosophila: "syn20673251"
    assay_templates:
      rnaSeq: "sysbio.metadataTemplates-assay.rnaSeq"
  species_list:
    - "mouse or other animal model"
    - "human"
    - "drosophila"
  complete_columns:
    manifest:
      - "parent"
      - "path"
    individual:
      - "individualID"
    biospecimen:
      - "individualID"
      - "specimenID"
    assay:
      - "specimenID"
  contact_email: "nicole.kauer@synapse.org"

dev:
  production: FALSE

testing:
  samples_table: "syn22089767"
  include_biospecimen_type: TRUE
  templates:
    manifest_template: "syn20820080"
    individual_templates:
      human: "syn12973254"
      mouse or other animal model: "syn12973253"
    biospecimen_templates:
      mouse or other animal model:
        in vitro: "syn25955510"
        other: "syn12973252"
      human: "syn12973252"
      drosophila: "syn20673251"
    assay_templates:
      rnaSeq: "syn12973256"
      proteomics: "sysbio.metadataTemplates-assay.proteomics"
  complete_columns:
    manifest:
      - "parent"
    individual:
      - "individualID"
    biospecimen:
      - "individualID"
      - "specimenID"
    assay:
      - "specimenID"


amp-ad:
  app_url: "https://shinypro.synapse.org/users/nkauer/dccvalidator-ad/"
  parent: "syn21643404"
  annotations_table: "syn21459391"
  annotations_link: "https://shinypro.synapse.org/users/kwoo/amp-ad-metadata-dictionary/"
  teams:
    - "3405451"
  docs_tab:
    include_tab: TRUE
    include_upload_widget: FALSE
    tab_name: "Study Documentation"
    path_to_docs_markdown: "inst/study-documentation-amp-ad.Rmd"
  species_list:
    - "human"
    - "drosophila"
    - "MODEL-AD mouse model"
    - "other mouse or animal model"
  include_biospecimen_type: TRUE
  templates:
    individual_templates:
      human: "syn12973254"
      other mouse or animal model: "syn12973253"
      MODEL-AD mouse model: "syn21084071"
    biospecimen_templates:
      human:
        in vivo, postmortem, other: "syn12973252"
        in vitro: "syn25955510"
      other mouse or animal model:
        in vivo, postmortem, other: "syn12973252"
        in vitro: "syn25955510"
      MODEL-AD mouse model:
        in vivo, postmortem, other: "syn12973252"
        in vitro: "syn25955510"
      drosophila: "syn20673251"
    assay_templates:
      ATACseq: "syn22024364"
      autorad: "syn22087295"
      immunoassay: "syn22117582"
      proteomics: "syn12973255"
      single cell RNAseq: "syn21018360"
      wholeGenomeSeq: "syn21018358"
      wholeExomeSeq: "syn21078272"
      NanoString: "syn21082744"
      snpArray: "syn21372586"
      STARRSeq: "syn26125115"
      TMT quantitation: "syn21433357"
      methylationArray: "syn22036881"
      MRI: "syn22087332"
      PET: "syn22087299"
      16SrRNAseq: "syn24184375"
      metabolomics: "syn24216748"
      HI-C: "syn25671270"
      ChIPSeq: "syn22907810"
      bisulfiteSeq: "syn25830897"
  complete_columns:
    manifest:
      - "consortium"
      - "study"
      - "grant"
      - "fileFormat"
      - "parent"
      - "path"
    individual:
      - "individualID"
    biospecimen:
      - "individualID"
      - "specimenID"
    assay:
      - "specimenID"
  contact_email: "AMPAD_SageAdmin@synapse.org"

pec:
  app_url: "https://shinypro.synapse.org/users/kmontgomery/apps_w_oauth/dccvalidator/"
  parent: "syn21763123"
  path_to_markdown: "inst/using-the-dccvalidator-pec.Rmd"
  study_table: "syn20968992"
  samples_table: "syn22175287"
  annotations_table: "syn20981788"
  annotations_link: "https://www.synapse.org/#!Synapse:syn20729790"
  templates_link: "https://www.synapse.org/#!Synapse:syn20729790"
  docs_tab:
    include_tab: TRUE
    include_upload_widget: FALSE
    tab_name: "Study Documentation"
    path_to_docs_markdown: "inst/study-documentation-pec.Rmd"
  teams:
    - "3323356"
  include_biospecimen_type: TRUE
  templates:
    manifest_template: "syn20782058"
    individual_templates:
      human: "syn20781820"
      animal: "syn21053116"
    biospecimen_templates:
      human:
        in vivo, postmortem, other: "syn20768131"
        in vitro: "syn26011297"
      other mouse or animal model:
        in vivo, postmortem, other: "syn20768131"
        in vitro: "syn26011297"
    assay_templates:
      ATACSeq: "syn20768526"
      bisulfiteSeq: "syn23017098"
      ChIPSeq: "syn21861858"
      HI-C: "syn21680758"
      immunoassay: "syn25805392"
      methylationArray: "syn25805391"
      rnaSeq: "syn20768650"
      snpArray: "syn21680759"
      STARRSeq: "syn26011215"
      TMT quantitation: "syn21680761"
      wholeGenomeSeq: "syn20980993"
  species_list:
    - "human"
    - "animal model"
  complete_columns:
    manifest:
      - "consortium"
      - "study"
      - "grant"
      - "fileFormat"
      - "parent"
      - "path"
    individual:
      - "individualID"
      - "individualIdSource"
      - "species"
      - "reportedGender"
      - "postmortem"
      - "primaryDiagnosis"
    biospecimen:
      - "individualID"
      - "specimenID"
      - "organ"
      - "tissue"
      - "nucleicAcidSource"
    assay:
      - "specimenID"
  contact_email: "PEC_SageAdmin@synapse.org"

veoibd:
  app_url: "https://shinypro.synapse.org/users/nkauer/dccvalidator-veoibd/"
  parent: "syn25556537"
  path_to_markdown: "inst/using-the-dccvalidator-veoibd.Rmd"
  study_table: "syn25557724"
  samples_table: "syn25557826"
  annotations_table: "syn25558026"
  annotations_link: "https://www.synapse.org/#!Synapse:syn20729790"
  templates_link: "https://www.synapse.org/#!Synapse:syn20729790"
  docs_tab:
    include_tab: TRUE
    include_upload_widget: FALSE
    tab_name: "Study Documentation"
    path_to_docs_markdown: "inst/study-documentation-pec.Rmd"
  teams:
    - "3382930"
    - "3425042"
  templates:
    manifest_template: "syn20782058"
    individual_templates:
      human: "syn20781820"
      animal: "syn21053116"
    biospecimen_templates:
      animal model: "syn20768131"
      human: "syn20768131"
    assay_templates:
      wholeGenomeSeq: "syn20980993"
      rnaSeq: "syn20768650"
      ATACSeq: "syn20768526"
      TMT quantitation: "syn21680761"
      HI-C: "syn21680758"
      snpArray: "syn21680759"
      ChIPSeq: "syn21861858"
      bisulfiteSeq: "syn23017098"
  species_list:
    - "human"
    - "animal model"
  complete_columns:
    manifest:
      - "consortium"
      - "study"
      - "grant"
      - "fileFormat"
      - "parent"
      - "path"
    individual:
      - "individualID"
      - "individualIdSource"
      - "species"
      - "reportedGender"
      - "postmortem"
      - "primaryDiagnosis"
    biospecimen:
      - "individualID"
      - "specimenID"
      - "organ"
      - "tissue"
      - "nucleicAcidSource"
    assay:
      - "specimenID"
  contact_email: "cmolitor@synapse.org"
