---
title: "AMP-AD Study Documentation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{amp-ad-study-documentation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Study Documentation

This information should be similar to a materials and methods section in a paper. An example of what a study should include can be found [here](https://adknowledgeportal.synapse.org/Explore/Studies/DetailsPage?Study=syn8391648){target="_blank"} for an animal model study and [here](https://adknowledgeportal.synapse.org/Explore/Studies/DetailsPage?Study=syn3159438){target="_blank"} for a human study. If you wish, also provide an acknowledgement statment and/or reference that should be included in publications resulting from secondary data use; examples can be found in the Acknowledgement sections of the studies linked above. This can be provided as part of the study documentation text.

## Study Description

Each study should be given both a descriptive and an abbreviated name. The abbreviation will be used to annotate all content associated with the study. For a study with a human cohort, the study description should include:

- study type (randomized controlled study, prospective observational study, case-control study, or post-mortem study)
disease focus
- diagnostic criteria and inclusion/exclusion criteria of study participants
- (for post mortem studies) the brain bank name(s) and links to website(s)

For a study with an animal model cohort, the study description should include:

- species
- treatments
- (if genetically modified) genotype and genetic background. Provide a link to the strain datasheet(s) if a commercial model, or a description of how it was created if not.

For studies using in-vitro cell culture, the study description should include:

- species
- cell type
- cell culture information (such as primary or immortalized cell line, passage, treatments, differentiation). If a commercial cell line, provide a link.
Include citations for more study information if available.

## Assay Description

For each assay, provide a summary of **sample processing**, **data generation**, and **data processing**, including which organs and tissues the samples came from. For other tests (such as cognitive assessments or imaging), include a description of how the test was done. Include links for any commercial equipment or tools, code repositories, and citations for more information, if available.

Detailed protocols are highly recommended. These can be uploaded as pdf together with the data-files, or as links to protocol repositories such as [protocols.io](https://www.protocols.io/){target="_blank"} or [Open Lab Book](https://theolb.readthedocs.io/en/latest/index.html#){target="_blank"}.
